language: python
os: linux

cache:
  - pip

jobs:
  include:
    - python: 3.6
      env: TOX_ENV=format
    - python: 3.6
      env: TOX_ENV=typing
    - python: 3.6
      env: TOX_ENV=py3.6-django2.2
    - python: 3.6
      env: TOX_ENV=py3.6-django3.0
    - python: 3.7
      env: TOX_ENV=py3.7-django2.2
    - python: 3.7
      env: TOX_ENV=py3.7-django3.0
    - python: 3.8
      env: TOX_ENV=py3.8-django2.2
    - python: 3.8
      env: TOX_ENV=py3.8-django3.0

install:
  - sudo apt-get update
  - sudo apt-get install xmlsec1
  - pip install --upgrade pip tox

script:
    - tox -e $TOX_ENV
